In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/content/weatherAUS.csv', encoding='utf-8',
                 usecols=['Date', 'Location','MinTemp', 'MaxTemp'])

In [29]:
# Drop records where target MinTemp= Nan or MaxTemp=NaN
df = df.dropna(subset=["MinTemp", "MaxTemp"])

In [31]:
# convert dates to year-months
df["Year-Month"] = (pd.to_datetime(df["Date"], yearfirst=True)).dt.strftime("%Y-%m")

In [32]:
# Derive median daily temperature (mid point between Daily Max and Daily Min)
df["MedTemp"] = df[["MinTemp", "MaxTemp"]].median(axis=1)

In [33]:
df

             Date      Location  MinTemp  MaxTemp Year-Month  MedTemp
0      2008-12-01        Albury     13.4     22.9    2008-12    18.15
1      2008-12-02        Albury      7.4     25.1    2008-12    16.25
2      2008-12-03        Albury     12.9     25.7    2008-12    19.30
3      2008-12-04        Albury      9.2     28.0    2008-12    18.60
4      2008-12-05        Albury     17.5     32.3    2008-12    24.90
...           ...           ...      ...      ...        ...      ...
10806  2014-01-12  CoffsHarbour     17.5     27.2    2014-01    22.35
10807  2014-01-13  CoffsHarbour     17.3     27.3    2014-01    22.30
10808  2014-01-14  CoffsHarbour     18.3     27.1    2014-01    22.70
10809  2014-01-15  CoffsHarbour     17.8     28.1    2014-01    22.95
10810  2014-01-16  CoffsHarbour     19.2     28.0    2014-01    23.60

[10741 rows x 6 columns]

**Aggregate**

In [34]:
df2 = df[["Location", "Year-Month", "MedTemp"]].copy()

In [35]:
# Calculate monthly average temperature for each location
df2 = df2.groupby(["Location", "Year-Month"], as_index=False)["MedTemp"].mean()

In [36]:
# Transpose dataframe
# Pivot to wide format
df2_pivot = df2.pivot(index="Location", columns="Year-Month", values="MedTemp")

In [37]:
df2_pivot

Year-Month,2008-12,2009-01,2009-02,2009-03,2009-04,2009-05,2009-06,2009-07,2009-08,2009-09,...,2016-09,2016-10,2016-11,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06
Location,,,,,,,,,,,,,,,,,,,,,
Albury,20.401613,25.485484,25.439286,20.535484,15.410000,11.716129,9.206667,8.201613,9.932258,11.951786,...,12.213333,13.617742,18.170000,22.677419,25.298387,23.239286,23.067742,15.516667,11.417742,7.972
BadgerysCreek,NaN,24.467742,22.948214,20.877419,17.305000,14.312903,11.769643,10.727419,12.520968,15.558333,...,14.766667,17.037097,21.485000,25.065385,26.430645,25.107143,22.050000,17.205000,14.372581,12.766
Cobar,NaN,29.264516,26.864286,24.611290,18.898333,14.756452,12.123333,10.833871,14.095161,16.546667,...,13.121667,17.475806,22.846667,27.277419,30.686207,29.042857,26.117742,19.016667,14.582258,11.576
CoffsHarbour,NaN,23.301613,23.274074,22.158065,19.828333,16.774194,14.343333,13.509677,16.058065,17.341667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
df2_pivot = df2_pivot.drop(
    ["Dartmoor", "Katherine", "Melbourne", "Nhil", "Uluru"],
    axis=0, errors="ignore"
)

In [39]:
df2_pivot.columns

Index(['2008-12', '2009-01', '2009-02', '2009-03', '2009-04', '2009-05',
       '2009-06', '2009-07', '2009-08', '2009-09', '2009-10', '2009-11',
       '2009-12', '2010-01', '2010-02', '2010-03', '2010-04', '2010-05',
       '2010-06', '2010-07', '2010-08', '2010-09', '2010-10', '2010-11',
       '2010-12', '2011-01', '2011-02', '2011-03', '2011-05', '2011-06',
       '2011-07', '2011-08', '2011-09', '2011-10', '2011-11', '2011-12',
       '2012-01', '2012-02', '2012-03', '2012-04', '2012-05', '2012-06',
       '2012-07', '2012-08', '2012-09', '2012-10', '2012-11', '2013-01',
       '2013-03', '2013-04', '2013-05', '2013-06', '2013-07', '2013-08',
       '2013-09', '2013-10', '2013-11', '2013-12', '2014-01', '2014-02',
       '2014-03', '2014-04', '2014-05', '2014-06', '2014-07', '2014-08',
       '2014-09', '2014-10', '2014-11', '2014-12', '2015-01', '2015-02',
       '2015-03', '2015-04', '2015-05', '2015-06', '2015-07', '2015-08',
       '2015-09', '2015-10', '2015-11', '2015-12', '2016-01', '2016-02',
       '2016-03', '2016-04', '2016-05', '2016-06', '2016-07', '2016-08',
       '2016-09', '2016-10', '2016-11', '2016-12', '2017-01', '2017-02',
       '2017-03', '2017-04', '2017-05', '2017-06'],
      dtype='object', name='Year-Month')

In [41]:
# remove months with lots of missing data

months_to_drop = [
    '2007-11', '2007-12',
    '2008-01', '2008-02', '2008-03', '2008-04',
    '2008-05', '2008-06', '2008-07', '2008-08',
    '2008-09', '2008-10', '2008-11', '2008-12',
    '2017-01', '2017-02', '2017-03',
    '2017-04', '2017-05', '2017-06'
]

df2_pivot = df2_pivot.drop(columns=months_to_drop, errors='ignore')

In [42]:
df2_pivot

Year-Month,2009-01,2009-02,2009-03,2009-04,2009-05,2009-06,2009-07,2009-08,2009-09,2009-10,...,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08,2016-09,2016-10,2016-11,2016-12
Location,,,,,,,,,,,,,,,,,,,,,
Albury,25.485484,25.439286,20.535484,15.410000,11.716129,9.206667,8.201613,9.932258,11.951786,14.595161,...,23.290323,17.580000,13.069355,9.500000,9.517742,9.625806,12.213333,13.617742,18.170000,22.677419
BadgerysCreek,24.467742,22.948214,20.877419,17.305000,14.312903,11.769643,10.727419,12.520968,15.558333,16.646429,...,22.938710,19.743333,15.164516,12.613333,12.053226,11.940323,14.766667,17.037097,21.485000,25.065385
Cobar,29.264516,26.864286,24.611290,18.898333,14.756452,12.123333,10.833871,14.095161,16.546667,19.229032,...,25.532258,21.925000,15.651613,11.528333,10.969355,11.638710,13.121667,17.475806,22.846667,27.277419
CoffsHarbour,23.301613,23.274074,22.158065,19.828333,16.774194,14.343333,13.509677,16.058065,17.341667,19.064516,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
# Add missing months 2011-04, 2011-04, 2011-04 and impute data
df2_pivot['2011-04']=(df2_pivot['2011-03']+df2_pivot['2011-05'])/2
df2_pivot['2012-12']=(df2_pivot['2012-11']+df2_pivot['2013-01'])/2
df2_pivot['2013-02']=(df2_pivot['2013-01']+df2_pivot['2013-03'])/2

In [44]:
# Sort columns so Year-Months ar3e in the correct order
df2_pivot = df2_pivot.reindex(sorted(df2_pivot.columns), axis=1)

In [45]:
import plotly.graph_objects as go

In [46]:
# Plot average monthly temperature derived from daily medians for each location
fig = go.Figure()
for location in df2_pivot.index:
    fig.add_trace(go.Scatter(x=df2_pivot.loc[location, :].index,
                             y=df2_pivot.loc[location, :].values,
                             mode='lines', name=location,
                             opacity=0.8, line=dict(width=1)
                            ))

In [47]:
# Change chart background color
fig.update_layout(dict(plot_bgcolor = 'white'), showlegend=True)

# Update axes lines
fig.update_xaxes(showgrid=True, gridwidth=1, gridcolor='lightgrey',
                 zeroline=True, zerolinewidth=1, zerolinecolor='lightgrey',
                 showline=True, linewidth=1, linecolor='black',
                 title='Date'
                )

fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='lightgrey',
                 zeroline=True, zerolinewidth=1, zerolinecolor='lightgrey',
                 showline=True, linewidth=1, linecolor='black',
                 title='Degrees Celsius'
                )

# Set figure title
fig.update_layout(title=dict(text="Average Monthly Temperatures", font=dict(color='black')))

fig.show()

In [48]:
import numpy as np

In [49]:
def shaping(datain, timestep):
    # Convert input dataframe to array and flatten
    arr = datain.to_numpy().flatten()

    X_list, y_list = [], []
    for i in range(len(datain.columns) - 2 * timestep + 1):
        X_list.append(arr[i:i+timestep])
        y_list.append(arr[i+timestep:i+2*timestep])

    # Reshape input and target arrays
    X_out = np.array(X_list).reshape(-1, timestep, 1)
    y_out = np.array(y_list).reshape(-1, timestep, 1)
    return X_out, y_out

In [50]:
### Step 1 - Specify parameters
timestep = 18
location = "Canberra"

In [51]:
## Step 2 - Prepare data
# Split data into train and test dataframes
df_train = df2_pivot.iloc[:, :-2*timestep].copy()
df_test = df2_pivot.iloc[:, -2*timestep: ].copy()

In [52]:
# Select one location
dfloc_train = df_train[df_train.index==location].copy()
dfloc_test = df_test[df_test.index==location].copy()

In [53]:
# Use previously defined shaping function to reshape the data for LSTM
X_train, y_train = shaping(datain=dfloc_train, timestep=timestep)
X_test, y_test = shaping(datain=dfloc_test, timestep=timestep)

In [54]:
from tensorflow import keras # for building Neural Networks
from keras.models import Sequential # for creating a linear stack of layers for our Neural Network
from keras import Input # for instantiating a keras tensor
from keras.layers import Bidirectional, LSTM, RepeatVector, Dense, TimeDistributed # for creating layers inside the Neural Network

In [55]:
##### Step 3 - Specify the structure of a Neural Network
model = Sequential(name="LSTM-Model")
# Input Layer - need to speicfy the shape of inputs
model.add(Input(shape=(X_train.shape[1],X_train.shape[2]), name='Input-Layer'))
# Encoder Layer
model.add(Bidirectional(LSTM(units=32, activation='tanh', recurrent_activation='sigmoid', stateful=False), name='Hidden-LSTM-Encoder-Layer'))
# Repeat Vector
model.add(RepeatVector(y_train.shape[1], name='Repeat-Vector-Layer'))
# Decoder Layer
model.add(Bidirectional(LSTM(units=32, activation='tanh', recurrent_activation='sigmoid', stateful=False, return_sequences=True), name='Hidden-LSTM-Decoder-Layer'))
# Output Layer, Linear(x) = x
model.add(TimeDistributed(Dense(units=1, activation='linear'), name='Output-Layer'))

In [59]:
##### Step 4 - Compile the model
model.compile(
    optimizer='adam', loss='mean_squared_error',
    metrics=['mean_squared_error', 'mean_absolute_error']
)

In [ ]:
## step - 5
history = model.fit(X_train, y_train,
    batch_size=1, epochs=50,
    validation_split=0.2, shuffle=True, verbose=0
)

In [ ]:
##### Step 6 - Use model to make predictions
# Predict esults on test data
pred_test = model.predict(X_test)

In [ ]:
##### Step 7 - Print Performance Summary
print("")
print('-------------------- Model Summary --------------------')
model.summary() # print model summary
print("")
print('-------------------- Weights and Biases --------------------')
print("Too many parameters to print but you can use the code provided if needed")
print("")
for layer in model.layers:
    print(layer.name)
    for item in layer.get_weights():
        print("  ", item)
print("")

In [ ]:
# Print the last value in the evaluation metrics contained within history file
print('-------------------- Evaluation on Training Data --------------------')
for item in history.history:
    print("Final", item, ":", history.history[item][-1])
print("")

In [ ]:
# Evaluate the model on the test data using "evaluate"
print('-------------------- Evaluation on Test Data --------------------')
results = model.evaluate(X_test, y_test)
print("")

In [ ]:
# Plot average monthly temperatures (actual and predicted) for test (out of time) data
fig = go.Figure()

# Trace for actual temperatures
fig.add_trace(go.Scatter(x=np.array(dfloc_test.columns),
                         y=np.array(dfloc_test.values).flatten(),
                         mode='lines',
                         name='Average Monthly Temperatures - Actual (Test)',
                         opacity=0.8,
                         line=dict(color='black', width=1)
                        ))

# Trace for predicted temperatures
fig.add_trace(go.Scatter(x=np.array(dfloc_test.columns[-timestep:]),
                         y=pred_test.flatten(),
                         mode='lines',
                         name='Average Monthly Temperatures - Predicted (Test)',
                         opacity=0.8,
                         line=dict(color='red', width=1)
                        ))

# Change chart background color
fig.update_layout(dict(plot_bgcolor = 'white'))

# Update axes lines
fig.update_xaxes(showgrid=True, gridwidth=1, gridcolor='lightgrey',
                 zeroline=True, zerolinewidth=1, zerolinecolor='lightgrey',
                 showline=True, linewidth=1, linecolor='black',
                 title='Year-Month'
                )

fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='lightgrey',
                 zeroline=True, zerolinewidth=1, zerolinecolor='lightgrey',
                 showline=True, linewidth=1, linecolor='black',
                 title='Degrees Celsius'
                )

# Set figure title
fig.update_layout(title=dict(text="Average Monthly Temperatures", font=dict(color='black')),
                  legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1)
                 )
fig.show()